### ISSUE TITLE
Platform Exception (channel-error, Unable to establish connection on channel)

### ISSUE THREAD

**Issue by firetiger8** [mrtungdev/flutter_epson_epos#10]
Hi mrtungdev, i have epson TM-U220, and I am using epson_epos package because the package used the ePOS2.jar .

But i get this error when running my app in emulator : 

 `I/flutter (11500): PlatformException(channel-error, Unable to establish connection on channel., null, null)`

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.22000.1219], locale en-ID)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.73.1)
[√] Connected device (5 available)
[√] HTTP Host Availability

My Pubspec.yaml : 
```
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: # Add this line
    sdk: flutter   
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  dio: ^4.0.6
  hive: ^2.2.2
  flutter_secure_storage: ^5.0.2
  get: ^4.6.5
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  dotted_line: ^3.1.0
  easy_debounce: ^2.0.2+1
  syncfusion_flutter_datagrid: ^20.2.36
  image_picker: ^0.8.5+3
  dropdown_search: ^5.0.2
  http: ^0.13.4
  syncfusion_flutter_datepicker: ^20.2.40
  device_preview: ^1.1.0
  syncfusion_localizations: ^20.2.43
  encrypt: ^5.0.1
  responsive_framework: ^0.2.0
  permission_handler: ^8.1.6
  image: ^3.2.0
  font_awesome_flutter: ^10.2.1
  hive_generator: ^1.1.3
  esc_pos_utils_plus: ^2.0.1+3
  print_bluetooth_thermal: ^1.0.5
  epson_epos: ^0.0.2 
```

Thank you
